# Generated by Django 6.0.5 on 2026-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_emotion', models.CharField(max_length=50)),
                ('voice_confidence', models.FloatField()),
                ('face_emotion', models.CharField(max_length=50)),
                ('face_confidence', models.FloatField()),
                ('final_emotion', models.CharField(max_length=50)),
                ('final_confidence', models.FloatField()),
                ('stress_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmotionRecord',
        ),
    ]
