# Generated by Django 5.0.6 on 2026-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_assessmentresult_delete_emotionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='text_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='text_emotion',
            field=models.CharField(default='No Data', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
